channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- coveralls
- coverage
- numpy =2.2.1
- black =24.8.0
- h5py =3.12.1
- ase =3.23.0
- sphinxdft-data =0.0.1
- sphinxdft =3.1
- semantikon =0.0.12
- pint =0.24.4
