channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- coveralls
- coverage
- numpy =2.3.1
- black =24.8.0
- h5py =3.14.0
- ase =3.25.0
- sphinxdft-data =0.0.1
- semantikon =0.0.19
- pint =0.24.4
